// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticket_Booking.Data;

#nullable disable

namespace Ticket_Booking.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260106032729_SyncModel")]
    partial class SyncModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Ticket_Booking.Models.DomainModels.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Ticket_Booking.Models.DomainModels.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Method")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Ticket_Booking.Models.DomainModels.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Ticket_Booking.Models.DomainModels.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AddOnPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<int>("BaggageOption")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("BoardingPassUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BookingGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsCheckedIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("MealOption")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int?>("OutboundTicketId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PNR")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentStatus")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<string>("QrCode")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReturnTicketId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatClass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TripId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookingGroupId")
                        .HasDatabaseName("IX_Tickets_BookingGroupId");

                    b.HasIndex("IsCheckedIn")
                        .HasDatabaseName("IX_Tickets_IsCheckedIn");

                    b.HasIndex("OutboundTicketId")
                        .IsUnique()
                        .HasDatabaseName("IX_Tickets_OutboundTicketId");

                    b.HasIndex("PNR")
                        .IsUnique()
                        .HasFilter("[PNR] IS NOT NULL");

                    b.HasIndex("ReturnTicketId")
                        .IsUnique()
                        .HasDatabaseName("IX_Tickets_ReturnTicketId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Tickets_Type");

                    b.HasIndex("UserId");

                    b.HasIndex("BookingGroupId", "Type")
                        .HasDatabaseName("IX_Tickets_BookingGroupId_Type");

                    b.HasIndex("TripId", "SeatNumber")
                        .HasDatabaseName("IX_Tickets_TripId_SeatNumber");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Ticket_Booking.Models.DomainModels.TicketChangeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChangeFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("NewTicketId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginalTicketId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceDifference")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmountPaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NewTicketId");

                    b.HasIndex("OriginalTicketId");

                    b.ToTable("TicketChangeHistories");
                });

            modelBuilder.Entity("Ticket_Booking.Models.DomainModels.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BusinessPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessSeats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Distance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EconomyPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("EconomySeats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstimatedDuration")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FirstClassPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstClassSeats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaneName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PriceLastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RoundTripDiscountPercent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Ticket_Booking.Models.DomainModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ticket_Booking.Models.DomainModels.Company", b =>
                {
                    b.HasOne("Ticket_Booking.Models.DomainModels.User", "Owner")
                        .WithMany("Companies")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Ticket_Booking.Models.DomainModels.Payment", b =>
                {
                    b.HasOne("Ticket_Booking.Models.DomainModels.Ticket", "Ticket")
                        .WithOne("Payment")
                        .HasForeignKey("Ticket_Booking.Models.DomainModels.Payment", "TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Ticket_Booking.Models.DomainModels.Review", b =>
                {
                    b.HasOne("Ticket_Booking.Models.DomainModels.Company", "Company")
                        .WithMany("Reviews")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ticket_Booking.Models.DomainModels.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ticket_Booking.Models.DomainModels.Ticket", b =>
                {
                    b.HasOne("Ticket_Booking.Models.DomainModels.Ticket", "OutboundTicket")
                        .WithOne()
                        .HasForeignKey("Ticket_Booking.Models.DomainModels.Ticket", "OutboundTicketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ticket_Booking.Models.DomainModels.Ticket", "ReturnTicket")
                        .WithOne()
                        .HasForeignKey("Ticket_Booking.Models.DomainModels.Ticket", "ReturnTicketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ticket_Booking.Models.DomainModels.Trip", "Trip")
                        .WithMany("Tickets")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ticket_Booking.Models.DomainModels.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OutboundTicket");

                    b.Navigation("ReturnTicket");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ticket_Booking.Models.DomainModels.TicketChangeHistory", b =>
                {
                    b.HasOne("Ticket_Booking.Models.DomainModels.Ticket", "NewTicket")
                        .WithMany()
                        .HasForeignKey("NewTicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ticket_Booking.Models.DomainModels.Ticket", "OriginalTicket")
                        .WithMany()
                        .HasForeignKey("OriginalTicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NewTicket");

                    b.Navigation("OriginalTicket");
                });

            modelBuilder.Entity("Ticket_Booking.Models.DomainModels.Trip", b =>
                {
                    b.HasOne("Ticket_Booking.Models.DomainModels.Company", "Company")
                        .WithMany("Trips")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Ticket_Booking.Models.DomainModels.Company", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Ticket_Booking.Models.DomainModels.Ticket", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Ticket_Booking.Models.DomainModels.Trip", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Ticket_Booking.Models.DomainModels.User", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Reviews");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
